### ISSUE TITLE
Limits dosen't work

### ISSUE THREAD

**Issue by fmohican** [xGlenor/PreciousStones#1]
Hello,

I use your build for my 1.19 server, but the permissions preciousstone.limit dosen't work.

I also tried the limit from config files with `limits: 1` or `max-per-player: 1` but dosen't work.....

Would you like to verify?

**Comment by durajg01** [comment]
Hi @fmohican , forgive me for only now. I am literally working on this plugin when I find some time. Could you please show what your configuration file looks like?

**Comment by fmohican** [comment]
Hi @xGlenor thanks for anwser and don't worry about time, we all prioritize certain things, well back to issues...

Config: https://gist.github.com/fmohican/a81c6ed81ddd7dbb23bdad2069f77daa

I also tied to limit via permissions, but it also fails...

**Comment by durajg01** [comment]
@fmohican What version of the plugin do you have? In the sense of where did you download it from?

**Comment by fmohican** [comment]
I build from your repo with `mvn package`

**Comment by durajg01** [comment]
It's current yes?

**Comment by fmohican** [comment]
I think its a month or so ago...

**Comment by durajg01** [comment]
I have uploaded your configuration and at my place everything works. If you have limits assigned to a group, for example.
```
  limits:
  - 2
  - 3
```
You must use the following permissions:
- preciousstones.limit1
- preciousstones.limit2

**Comment by fmohican** [comment]
hmm oke let me a day to try, I will also rebuild from source

**Comment by durajg01** [comment]
Is everything working? @fmohican
